:connection:
  :adapter: sqlite3
  :database: imageboard.db

# Max image filesize in bytes.
:max_filesize: 2097152

# Thread post reply limit.
:reply_limit: 300

# Thread image reply limit.
:image_limit: 150

# Default poster name.
:default_name: Anonymous

# Used in places that refer to the site.
:site_name: wirechan

# Hash length to use for image filenames.
# Note that this affects the length of links to images on your site.
:url_hash_size: 32

# Contact email.
:email: admin@wirechan.org

# Secret token used for sessions. CHANGE THIS.
:secret: your secret here

# Maximum post length.
:character_limit: 1024
